name: countdown_widget
description: A package timer works correctly even if the app is locked.
version: 2.0.2
homepage: https://github.com/tbm98/countdown_widget
repository: https://github.com/tbm98/countdown_widget
issue_tracker: https://github.com/tbm98/countdown_widget/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  mutex: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
